// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/njun10/mylibrary/common/model/internal"
)

// Category is the golang structure for table category.
type Category internal.Category

// Fill with you ideas below.
