// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/njun10/mylibrary/common/model/internal"
)

// Location is the golang structure for table location.
type Location internal.Location

// Fill with you ideas below.
