// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/njun10/mylibrary/common/model/internal"
)

// MarketInfo is the golang structure for table market_info.
type MarketInfo internal.MarketInfo

// Fill with you ideas below.
