// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/njun10/mylibrary/common/model/internal"
)

// Product is the golang structure for table product.
type Product internal.Product

// Fill with you ideas below.
