// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/njun10/mylibrary/common/dao/internal"
)

// locationDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type locationDao struct {
	internal.LocationDao
}

var (
	// Location is globally public accessible object for table location operations.
	Location = locationDao{
		internal.Location,
	}
)

// Fill with you ideas below.
