// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/njun10/mylibrary/common/dao/internal"
)

// marketInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type marketInfoDao struct {
	internal.MarketInfoDao
}

var (
	// MarketInfo is globally public accessible object for table market_info operations.
	MarketInfo = marketInfoDao{
		internal.MarketInfo,
	}
)

// Fill with you ideas below.
