// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// Category is the golang structure for table category.
type Category struct {
	Id          uint   `orm:"id"           json:"id"`          //
	Upid        int    `orm:"upid"         json:"upid"`        // 上级类目ID
	Name        string `orm:"name"         json:"name"`        // 类目名称
	PinyinS     string `orm:"pinyin_s"     json:"pinyinS"`     // 拼音简写
	PinyinA     string `orm:"pinyin_a"     json:"pinyinA"`     // 拼音全拼
	Weight      uint   `orm:"weight"       json:"weight"`      //
	Status      uint   `orm:"status"       json:"status"`      //
	CreatedTime int    `orm:"created_time" json:"createdTime"` //
	UpdatedTime int    `orm:"updated_time" json:"updatedTime"` //
}
