// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// Location is the golang structure for table location.
type Location struct {
	Id       uint    `orm:"id"        json:"id"`       //
	Upid     uint    `orm:"upid"      json:"upid"`     // 上级行政区域ID
	Path     string  `orm:"path"      json:"path"`     // 行政区域的ID路径
	Name     string  `orm:"name"      json:"name"`     // 上级行政区域名称
	FullName string  `orm:"full_name" json:"fullName"` // 上级行政区域  全路径全称
	Level    int     `orm:"level"     json:"level"`    // 默认省级
	IsLeaf   int     `orm:"is_leaf"   json:"isLeaf"`   // 是否叶节点
	Lat      float64 `orm:"lat"       json:"lat"`      // 纬度
	Lng      float64 `orm:"lng"       json:"lng"`      // 经度
	Geohash  string  `orm:"geohash"   json:"geohash"`  //
	Status   int     `orm:"status"    json:"status"`   // 默认开启
}
