// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// MarketInfo is the golang structure for table market_info.
type MarketInfo struct {
	Id          uint    `orm:"id"           json:"id"`          //
	Name        string  `orm:"name"         json:"name"`        //
	AliasName   string  `orm:"alias_name"   json:"aliasName"`   //
	Pic         string  `orm:"pic"          json:"pic"`         //
	Intro       string  `orm:"intro"        json:"intro"`       //
	Addr        string  `orm:"addr"         json:"addr"`        //
	Status      uint    `orm:"status"       json:"status"`      //
	ProvinceId  uint    `orm:"province_id"  json:"provinceId"`  // 省份ID
	CityId      uint    `orm:"city_id"      json:"cityId"`      // 城市ID
	CountyId    int     `orm:"county_id"    json:"countyId"`    //
	LocationId  int     `orm:"location_id"  json:"locationId"`  //
	Lat         float64 `orm:"lat"          json:"lat"`         // 纬度
	Lng         float64 `orm:"lng"          json:"lng"`         // 经度
	Geohash     string  `orm:"geohash"      json:"geohash"`     //
	UpdatedTime string  `orm:"updated_time" json:"updatedTime"` //
	CreatedTime string  `orm:"created_time" json:"createdTime"` //
	Level       int     `orm:"level"        json:"level"`       //
}
